<a href="https://colab.research.google.com/github/Ellisetr/Intelligent-Systems-and-Technologies/blob/main/%D0%98%D0%A1%D0%A2_1_2(%D1%80%D1%83%D1%87%D0%BD%D0%BE%D0%B9_%D1%80%D0%B5%D0%B6%D0%B8%D0%BC).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from itertools import *

In [ ]:
small_df = pd.read_excel('https://docs.google.com/spreadsheets/d/1aZTDk8rHtzlCi09DDvI-w1wEERD2aUoL/export?format=xlsx',header=None)
small_df

,0,1,2,3,4,5,6
0,Булочка с маком,Русианно,Эспрессо,Булочка с корицей,Чёрный чай,Какао,Пражский
1,Чёрный чай,Какао,Булочка с маком,Пражский,Мокка,Эспрессо,NaN
2,Пражский,Булочка с корицей,Эспрессо,Латте,Булочка с маком,Зелёный чай,NaN
3,Круасан,Эспрессо,Наполеон,Латте,Мокка,NaN,NaN
4,Мокка,Латте,Булочка с маком,Эспрессо,NaN,NaN,NaN
5,Булочка с корицей,Пражский,Круасан,Эспрессо,Булочка с маком,NaN,NaN
6,Чёрный чай,Зелёный чай,Эспрессо,Круасан,Русианно,Латте,NaN
7,Русианно,Круасан,Зелёный чай,Булочка с маком,Эспрессо,Латте,NaN
8,Круасан,Русианно,Булочка с корицей,Наполеон,Какао,Булочка с маком,NaN
9,Латте,Наполеон,Булочка с корицей,Пражский,NaN,NaN,NaN
10,Чёрный чай,Наполеон,Пражский,Булочка с корицей,Эспрессо,Зелёный чай,Булочка с маком
11,Латте,Пражский,Какао,NaN,NaN,NaN,NaN
12,Круасан,Пражский,Русианно,Чёрный чай,Эспрессо,NaN,NaN
13,Латте,Мокка,Зелёный чай,NaN,NaN,NaN,NaN
14,Латте,Булочка с маком,Какао,Пражский,Эспрессо,Мокка,Булочка с корицей
15,Булочка с маком,Булочка с корицей,Латте,Пражский,NaN,NaN,NaN
16,Латте,Какао,Эспрессо,NaN,NaN,NaN,NaN
17,Латте,Круасан,Чёрный чай,Булочка с корицей,Зелёный чай,NaN,NaN
18,Латте,Булочка с корицей,Булочка с маком,Пражский,NaN,NaN,NaN
19,Какао,Латте,Наполеон,Зелёный чай,Булочка с корицей,Русианно,Булочка с маком
20,Мокка,Эспрессо,Наполеон,Русианно,NaN,NaN,NaN
21,Зелёный чай,Латте,Чёрный чай,Булочка с маком,NaN,NaN,NaN
22,Булочка с маком,Булочка с корицей,Пражский,Русианно,NaN,NaN,NaN
23,Круасан,Латте,Какао,NaN,NaN,NaN,NaN
24,Эспрессо,Круасан,Наполеон,Какао,Чёрный чай,Русианно,Булочка с корицей
25,Латте,Чёрный чай,Мокка,Булочка с маком,Булочка с корицей,NaN,NaN
26,Мокка,Чёрный чай,Булочка с корицей,Наполеон,Латте,Круасан,Эспрессо
27,Русианно,Латте,Булочка с маком,Зелёный чай,NaN,NaN,NaN
28,Русианно,Латте,Зелёный чай,NaN,NaN,NaN,NaN
29,Эспрессо,Чёрный чай,Булочка с маком,Мокка,Русианно,NaN,NaN

Подготовка данных

In [ ]:
trans_from_df = small_df.values.tolist()
transactions = []
for rows in trans_from_df:
  clean_row = []
  for items in rows:
    if items is not np.nan:
      clean_row.append(items)
  transactions.append(clean_row) 

minsup = 0.2
minconf = 0.6
real_minsup = len(transactions)*minsup

Пускай у нас будет minsup = 0.2, minconf = 0.8

In [ ]:
unique = {}
unique['Single Items'] = {}
for lines in transactions:
  for items in lines:
    if items not in unique['Single Items']:
      unique['Single Items'][items] = 1
    else:
      unique['Single Items'][items] += 1
print('Общее количество элементов в таблице')
for keys in unique['Single Items']:
  print(keys,':',unique['Single Items'][keys])

Общее количество элементов в таблице
Булочка с маком : 17
Русианно : 12
Эспрессо : 16
Булочка с корицей : 15
Чёрный чай : 11
Какао : 9
Пражский : 12
Мокка : 9
Латте : 20
Зелёный чай : 10
Круасан : 10
Наполеон : 8

                   Single Items
Булочка с корицей            15
Булочка с маком              17
Зелёный чай                  10
Какао                         9
Круасан                      10
Латте                        20
Мокка                         9
Наполеон                      8
Пражский                     12
Русианно                     12
Чёрный чай                   11
Эспрессо                     16

In [ ]:
unique['Double Items']={}
for lines in transactions:
  for items in list(combinations((sorted(lines)),2)):
    if items not in unique['Double Items']:
      unique['Double Items'][items] = 1
    else:
      unique['Double Items'][items] += 1

to_del = []
for keys in unique['Double Items']:
  if unique['Double Items'][keys] < real_minsup:
    to_del.append(keys)
for keys in to_del:
  unique['Double Items'].pop(keys)

print('Общее количество 2-предметных наборов в таблице, которые подходят под MinSup')
for keys in sorted(unique['Double Items']):
  print(keys,':',unique['Double Items'][keys])

Общее количество 2-предметных наборов в таблице, которые подходят под MinSup
('Булочка с корицей', 'Булочка с маком') : 11
('Булочка с корицей', 'Латте') : 9
('Булочка с корицей', 'Наполеон') : 6
('Булочка с корицей', 'Пражский') : 9
('Булочка с корицей', 'Чёрный чай') : 6
('Булочка с корицей', 'Эспрессо') : 7
('Булочка с маком', 'Зелёный чай') : 6
('Булочка с маком', 'Латте') : 10
('Булочка с маком', 'Пражский') : 9
('Булочка с маком', 'Русианно') : 7
('Булочка с маком', 'Чёрный чай') : 6
('Булочка с маком', 'Эспрессо') : 9
('Зелёный чай', 'Латте') : 9
('Круасан', 'Латте') : 6
('Круасан', 'Эспрессо') : 7
('Латте', 'Мокка') : 6
('Латте', 'Пражский') : 6
('Латте', 'Эспрессо') : 8
('Мокка', 'Эспрессо') : 7
('Пражский', 'Эспрессо') : 7
('Русианно', 'Эспрессо') : 7
('Чёрный чай', 'Эспрессо') : 8

In [ ]:
unique['Triple Items'] = {}

for lines in transactions:
  for items in list(combinations((sorted(lines)),3)):
    if items not in unique['Triple Items']:
      unique['Triple Items'][items] = 1
    else:
      unique['Triple Items'][items] += 1

to_del = []
for keys in unique['Triple Items']:
  if unique['Triple Items'][keys] < real_minsup:
    to_del.append(keys)
for keys in to_del:
  unique['Triple Items'].pop(keys)

print('Общее количество 3-предметных наборов в таблице, которые подходят под MinSup')
for keys in sorted(unique['Triple Items']):
  print(keys,':',unique['Triple Items'][keys])

Общее количество 3-предметных наборов в таблице, которые подходят под MinSup
('Булочка с корицей', 'Булочка с маком', 'Латте') : 6
('Булочка с корицей', 'Булочка с маком', 'Пражский') : 8
('Булочка с маком', 'Пражский', 'Эспрессо') : 6

In [ ]:
unique['Quad Items'] = {}

for lines in transactions:
  for items in list(combinations((sorted(lines)),4)):
    if items not in unique['Quad Items']:
      unique['Quad Items'][items] = 1
    else:
      unique['Quad Items'][items] += 1

to_del = []
for keys in unique['Quad Items']:
  if unique['Quad Items'][keys] < real_minsup:
    to_del.append(keys)
for keys in to_del:
  unique['Quad Items'].pop(keys)

print('Общее количество 4-предметных наборов в таблице, которые подходят под MinSup')
for keys in sorted(unique['Quad Items']):
  print(keys,':',unique['Quad Items'][keys])

Общее количество 4-предметных наборов в таблице, которые подходят под MinSup

In [ ]:
# Для 2-ух элементов
rules = []
for keys in unique['Double Items']:
  conf = round(unique['Double Items'][keys]/unique['Single Items'][keys[1]],4)
  sup = round(unique['Double Items'][keys]/len(transactions),4)
  if conf >= minconf:
    rules.append([{keys[1]},{keys[0]},conf,sup])
    
  conf = round(unique['Double Items'][keys]/unique['Single Items'][keys[0]],4)
  sup = round(unique['Double Items'][keys]/len(transactions),4)
  if conf >= minconf:
    rules.append([{keys[0]},{keys[1]},conf,sup])

In [ ]:
rules1 = []
for keys in unique['Triple Items']:
  for lines in combinations(keys,2):
    conf = round(unique['Triple Items'][keys]/unique['Double Items'][lines],4)
    sup = round(unique['Triple Items'][keys]/len(transactions),4)
    if conf >= minconf:
      rules1.append([set(lines),(set(keys)-set(lines)),conf,sup])

  for lines in combinations(keys,2):
    conf = round(unique['Triple Items'][keys]/unique['Single Items'][list(set(keys)-set(lines))[0]],4)
    sup = round(unique['Triple Items'][keys]/len(transactions),4)
    if conf >= minconf:
      rules1.append([(set(keys)-set(lines)),set(lines),conf,sup])

In [ ]:
def print_rules(rules):
  for line in rules:
    print("{} -> {} (conf: {}, supp: {})".format(line[0],line[1],line[2],line[3]))

print_rules(rules)
print_rules(rules1)

{'Булочка с маком'} -> {'Булочка с корицей'} (conf: 0.6471, supp: 0.3667)
{'Булочка с корицей'} -> {'Булочка с маком'} (conf: 0.7333, supp: 0.3667)
{'Пражский'} -> {'Булочка с корицей'} (conf: 0.75, supp: 0.3)
{'Булочка с корицей'} -> {'Пражский'} (conf: 0.6, supp: 0.3)
{'Пражский'} -> {'Булочка с маком'} (conf: 0.75, supp: 0.3)
{'Чёрный чай'} -> {'Эспрессо'} (conf: 0.7273, supp: 0.2667)
{'Мокка'} -> {'Эспрессо'} (conf: 0.7778, supp: 0.2333)
{'Булочка с корицей'} -> {'Латте'} (conf: 0.6, supp: 0.3)
{'Зелёный чай'} -> {'Булочка с маком'} (conf: 0.6, supp: 0.2)
{'Зелёный чай'} -> {'Латте'} (conf: 0.9, supp: 0.3)
{'Круасан'} -> {'Латте'} (conf: 0.6, supp: 0.2)
{'Круасан'} -> {'Эспрессо'} (conf: 0.7, supp: 0.2333)
{'Мокка'} -> {'Латте'} (conf: 0.6667, supp: 0.2)
{'Наполеон'} -> {'Булочка с корицей'} (conf: 0.75, supp: 0.2)
{'Булочка с корицей', 'Булочка с маком'} -> {'Пражский'} (conf: 0.7273, supp: 0.2667)
{'Пражский', 'Булочка с корицей'} -> {'Булочка с маком'} (conf: 0.8889, supp: 0.2667)
{'Пражский', 'Булочка с маком'} -> {'Булочка с корицей'} (conf: 0.8889, supp: 0.2667)
{'Пражский'} -> {'Булочка с корицей', 'Булочка с маком'} (conf: 0.6667, supp: 0.2667)
{'Пражский', 'Булочка с маком'} -> {'Эспрессо'} (conf: 0.6667, supp: 0.2)
{'Булочка с маком', 'Эспрессо'} -> {'Пражский'} (conf: 0.6667, supp: 0.2)
{'Пражский', 'Эспрессо'} -> {'Булочка с маком'} (conf: 0.8571, supp: 0.2)
{'Латте', 'Булочка с корицей'} -> {'Булочка с маком'} (conf: 0.6667, supp: 0.2)
{'Латте', 'Булочка с маком'} -> {'Булочка с корицей'} (conf: 0.6, supp: 0.2)